if True:
    config = "my_qmix"
    env_config = "gymma"
    time_limit = 25
    key = "mpe:SimpleTag-1good-3adv-v0"
    pretrained_wrapper = "PretrainedTag"
    learner = 'my_q_learner'
    use_encoder = True
    train_schedule = "train"
    test_schedule = "test"
    name = "simple_tag_run_iter_10_ogn_4_ttmax_750000_tmax_1250000_lstm_zdim_32_64_xi_2.5"
    seeds = [0, 1, 2]
    cuda_device = [4, 5, 6]
    recorder_load_path = ""
    iterations = 10
    z_gen_hyper = False
    agent = "rnn_ns"
    teammate_agent = "rnn_ns"
    proxy_encoder = "lstm_ns"
    team_encoder = "lstm"
    use_contrastive_loss = True
    proxy_z_dim = 32
    team_z_dim = 64
    xi = 2.5
    teammate_t_max = 750000
    t_max = 1250000
    once_gen_num = 4
    pretrain_teammate_path = "pretrain_checkpoint/simple_tag_3adv/pretrain_teammate_path"
    pretrain_enc_path = "pretrain_checkpoint/simple_tag_3adv/pretrain_enc_path"
    test_recorder_load_path = "recorder_checkpoint/test_env_generate_seed2_mpe_SimpleTag-1good-3adv-v0_2022-12-26_19_58_40.376907_test_crp_0/0"
