# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "dynamic_episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval_or_tau: 200


# use the Q_Learner to train

obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

mac: "my_mac"
agent: "mlp_ns"
standardise_returns: False
standardise_rewards: True

agent_output_type: "q"
learner: "my_q_learner"
double_q: True
use_rnn: False
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

name: "my_qmix"


############################
######## New Params ########
############################
n_control: 2
proxy_hidden_dim: 64
team_hidden_dim: 64
vi_hidden_dim: 64
eta: .01
kernel: "rbf"
rbf_radius: 80.0
active_lower: 6
active_upper: 8
waiting_lower: 5
waiting_upper: 9
recorder_type: "type_recorder"
proxy_encoder: "mlp_ns"
team_encoder: "mlp"
min_logvar: -10.0
max_logvar: 0.5
contrastive_lambda_1: 1.0
contrastive_lambda_2: .4
vi_lambda_1: .001
vi_lambda_2: .0001
proxy_z_dim: 32
team_z_dim: 64
train_schedule: "base"
test_schedule: "base"
z_gen_hyper: False
use_encoder: True
